# miniconda bootstrap from conda-forge recipe

matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 35
      CONDA_PY_SPEC: 3.5
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - CONDA_PY: 36
      CONDA_PY_SPEC: 3.6
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - CONDA_PY: 37
      CONDA_PY_SPEC: 3.7
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"
    - CONDA_PY: 38
      CONDA_PY_SPEC: 3.8
      # appveyor doesn't come with this directory, so use 37's since we're creating an env anyway
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

platform:
  - x64

build: false

install:
  - cmd: call %CONDA_INSTALL_LOCN%\\Scripts\\activate.bat
  - cmd: set CONDA_PY=%CONDA_PY%
  - cmd: set CONDA_PY_SPEC=%CONDA_PY_SPEC%
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  - cmd: conda update -y -q conda
  - cmd: conda info -a
  - cmd: conda create -y -q -n test-env-%CONDA_PY% python=%CONDA_PY_SPEC% pip pyzmq tornado jupyter_client nbformat nbconvert nose
  - cmd: conda activate test-env-%CONDA_PY%
  - cmd: pip install -e .[test]

test_script:
  - pytest -s -v
